import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:news_app/core/colors_manager/colors_manager.dart';
import 'package:news_app/features/articales/articale_item.dart';
import 'package:news_app/models/category.dart';
import 'package:news_app/models/source.dart';

import '../../providers/articale.dart';


class SourcesView extends StatelessWidget {
  SourcesView({super.key, required this.category});

  CategoryModel category;
  List<Source> sources = [
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "2",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBc",
      description: "description",
      url: "http//BBc:sdas",
      category: "category",
      language: "en",
      country: "EG",
    ),
  ];
  List<Articale> articale = [
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Articale(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      auther: "ayther",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Container(

      child: Column(
        children: [
          DefaultTabController(
            length: sources.length,
            child: TabBar(
              isScrollable: true,
              tabAlignment: TabAlignment.start,
              indicatorColor: ColorsManager.white,
              unselectedLabelStyle: GoogleFonts.inter(
                color: ColorsManager.white,
                fontSize: 14,
                fontWeight: FontWeight.w500,
              ),
              dividerColor: Colors.transparent,
              labelStyle: GoogleFonts.inter(
                color: ColorsManager.white,
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
              tabs: sources.map((sources) => Tab(text: sources.name)).toList(),
            ),
          ),
          Expanded(
            child: ListView.separated(
              separatorBuilder: (context, index) => SizedBox(height: 15.h),
              itemCount: articale.length,
              itemBuilder: (context, index) => ArticaleItem(articale: articale[index]),
            ),
          )
        ],
      ),
    );
  }
}
